#!/usr/bin/env python3
"""Regenerate ``src/skillsentinel/__about__.py`` from git metadata.

Run this from CI before building wheels. In dev, you don't need to run it —
the placeholders in ``__about__.py`` are fine for local work.

Internal builds get full provenance. Public builds (``SKILLSENTINEL_PUBLIC_BUILD=1``)
strip everything an adversary could fingerprint.
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ABOUT_PATH = REPO_ROOT / "src" / "skillsentinel" / "__about__.py"


def _git(args: list[str], default: str = "unknown") -> str:
    try:
        return subprocess.check_output(  # noqa: S603
            ["git", *args], cwd=REPO_ROOT, stderr=subprocess.DEVNULL
        ).decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return default


def build_about_py(public: bool) -> str:
    if public:
        version = "SkillSentinel"
        build_date = ""
        sha = ""
    else:
        version = _git(["describe", "--tags", "--dirty", "--always"], default="0.0.0+unknown")
        build_date = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        sha = _git(["rev-parse", "--short=12", "HEAD"], default="unknown")

    return (
        '"""Generated by scripts/build_info.py — do not edit by hand."""\n'
        "from __future__ import annotations\n"
        "import os\n\n"
        f'__version__ = "{version}"\n'
        f'__build_date__ = "{build_date}"\n'
        f'__git_sha__ = "{sha}"\n\n'
        '_PUBLIC_MODE = os.environ.get("SKILLSENTINEL_PUBLIC_BUILD") == "1"\n\n'
        "if _PUBLIC_MODE:\n"
        '    __version__ = "SkillSentinel"\n'
        '    __build_date__ = ""\n'
        '    __git_sha__ = ""\n\n'
        "def version_string(verbose: bool = False) -> str:\n"
        "    if _PUBLIC_MODE:\n"
        '        return "SkillSentinel"\n'
        "    if not verbose:\n"
        '        return f"SkillSentinel {__version__}"\n'
        "    return (\n"
        '        f"SkillSentinel {__version__}\\n"\n'
        '        f"  Built:   {__build_date__}\\n"\n'
        '        f"  Commit:  {__git_sha__}"\n'
        "    )\n"
    )


def main() -> int:
    public = os.environ.get("SKILLSENTINEL_PUBLIC_BUILD") == "1"
    content = build_about_py(public=public)
    ABOUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {ABOUT_PATH} (public_mode={public})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
